info:
  name: getItem
  type: http
  seq: 1

http:
  method: GET
  url: "{{API_URL}}/item"
  body:
    type: json
    data: |2
      
        {
      //     "itemid" : "104.342.001",
          "itemidkeyword" : "",
          "itemnamekeyword" : "",
          "grouprekidkeyword" : "",
          "groupnamekeyword" : ""
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
